name = "brainsait-marketing-api"
main = "workers/api.js"
compatibility_date = "2024-08-19"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_NAME = "BrainSAIT Marketing Platform"
APP_VERSION = "2.0.0"
ENVIRONMENT = "production"