# Cloudflare Workers Configuration for BrainSAIT Marketing Platform
name = "brainsait-marketing"
main = "workers/api.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Account configuration
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Workers configuration
workers_dev = true
route = { pattern = "api.brainsait.com/*", zone_name = "brainsait.com" }

# Memory and CPU limits
limits = { cpu_ms = 50 }

# Environment variables for all environments
[vars]
APP_NAME = "BrainSAIT Marketing Platform"
APP_VERSION = "2.0.0"
LOG_LEVEL = "info"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = ["src", "workers", "config"]

# Pages build output directory
pages_build_output_dir = "dist"

# Asset uploading
[build.upload]
format = "modules"
dir = "dist"
main = "./workers/api.js"

# Development environment
[env.development]
name = "brainsait-marketing-dev"
route = { pattern = "api-dev.brainsait.com/*", zone_name = "brainsait.com" }

[env.development.vars]
ENVIRONMENT = "development"
DEBUG = "true"
API_BASE_URL = "https://api-dev.brainsait.com"
FRONTEND_URL = "https://dev.brainsait.com"

# Staging environment
[env.staging]
name = "brainsait-marketing-staging"
route = { pattern = "api-staging.brainsait.com/*", zone_name = "brainsait.com" }

[env.staging.vars]
ENVIRONMENT = "staging"
DEBUG = "false"
API_BASE_URL = "https://api-staging.brainsait.com"
FRONTEND_URL = "https://staging.brainsait.com"

# Production environment
[env.production]
name = "brainsait-marketing-prod"
route = { pattern = "api.brainsait.com/*", zone_name = "brainsait.com" }

[env.production.vars]
ENVIRONMENT = "production"
DEBUG = "false"
API_BASE_URL = "https://api.brainsait.com"
FRONTEND_URL = "https://app.brainsait.com"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"